name: Todo-API CI

on:
  workflow_dispatch:
    inputs:
      deployment_environment:
        type: choice
        description: Environment for Deployment
        default: none
        options: 
        - dev
        - prod
        - none
  push:
    paths:
      - 'TodoApi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_NAME }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push Docker image to ACR
      uses: docker/build-push-action@v2
      with:
        context: ./TodoApi
        file: ./TodoApi/Dockerfile
        push: true
        tags: ${{ secrets.AZURE_REGISTRY_NAME }}/todo-api:0.0.${{github.run_number}}

    - name: Deployment
      if: inputs.deployment_environment != 'none'
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets[format('{0}_SUBSCRIPTION',inputs.deployment_environment)] }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_VAR_environment: ${{inputs.deployment_environment}}
        TF_VAR_release_number: 0.0.${{github.run_number}}
      working-directory: ./TodoApi/terraform
      run: |
        terraform init -backend-config=${{inputs.deployment_environment}}.conf -input=false
        terraform apply -input=false -auto-approve